---

 - name: add openhpc repository
   yum: name={{ openhpc_release_rpm }} state=present

 - name: install ohpc-ganglia packages
   yum: name=ohpc-ganglia state=installed

 - name: find relevant chroot directories
   shell: "find /opt/ohpc/admin/images/ -maxdepth 1 -mindepth 1 -type d"
   register: chroot_dirs

 - name: install gmond into chroot image
   command: yum -y --installroot={{ item }} install ganglia-gmond-ohpc
   with_items:
     - "{{ chroot_dirs.stdout_lines }}"

 - name: add ganglia.conf to headnode
   template: src=gmond.conf.j2 dest=/etc/ganglia/gmond.conf

 - name: add ganglia.conf to vnfs
   template: src=gmond.conf.j2 dest={{item}}/etc/ganglia/gmond.conf
   with_items:
     - "{{ chroot_dirs.stdout_lines }}"

 - name: rebuild the vnfs 
   command: wwvnfs -y --chroot "{{ item }}"
   with_items:
     - "{{ chroot_dirs.stdout_lines }}"

 - fail: 
     msg: "CHECK THAT THE TEMPLATING WORKED"

# - name: configure httpd
#
# - name: start service on headnode (gmetad)
#
# - name: start service on computes (gmond)
