---

 - name: install prerequisites
    
   package:
     pkg: "{{ item }}"
     state: installed
   with_items:
     - "glibc"
     - golang
     - "golang-github-prometheus"
   become: yes
 
 - name: add prometheus to internal zone
   firewalld:
     zone: internal
     service: "prometheus"
     permanent: yes
     immediate: yes
     state: enabled
   become: yes

 - name: Open port 9090
   firewalld:
     zone: public
     permanent: yes
     immediate: yes
     state: enabled
     port: "9090/tcp"
   become: yes

 - name: reload firewalld
   command: firewall-cmd --reload
   become: yes

 - name: Make prometheus port exposed to all host
   replace:
     path: /etc/sysconfig/prometheus
     regexp: 'WEB_LISTEN_ADDRESS=127.0.0.1'
     replace: 'WEB_LISTEN_ADDRESS=0.0.0.0'
   become: yes

 - name: prometheus prometheus.conf
   template: src=prometheus.yml dest=/etc/prometheus/prometheus.yml
   become: yes

 - name: ensure prometheus is running
   service: name=prometheus state=restarted enabled=yes
   become: yes

 - name: Checking out prometheous slurm exporter source code
   git:
     repo: https://github.com/DImuthuUpe/prometheus-slurm-exporter
     dest: /opt/prometheus-slurm-exporter
     version: master
   become: yes

 - name: Download golang dependencies
   command: go mod download
   args:
     chdir: /opt/prometheus-slurm-exporter
   become: yes

 - name: Build prometheous node exporter
   command:  go build -o bin/prometheus-slurm-exporter
   args:
     chdir: /opt/prometheus-slurm-exporter
   become: yes

 - name: Stop slurm exporter service if running
   service: name=prometheus-slurm-exporter state=stopped
   become: yes
   ignore_errors: yes

 - name: Copy prometheus-slurm-exporter binary to /usr/bin
   command:  cp bin/prometheus-slurm-exporter /usr/bin/prometheus-slurm-exporter
   args:
     chdir: /opt/prometheus-slurm-exporter
   become: yes

 - name: Copy slurm exporter service file
   template: src=prometheus-slurm-exporter.service.j2 dest=/usr/lib/systemd/system/prometheus-slurm-exporter.service
   become: yes

 - name: Reload systemd
   command: systemctl daemon-reload
   become: yes

 - name: Start slurm exporter service
   service: name=prometheus-slurm-exporter state=restarted enabled=yes
   become: yes
